name: easy_web_view
description: A super simple webview for Flutter Web and Mobile
version: 1.4.0
homepage: https://github.com/rodydavis/easy_web_view
repository: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
publish_to: none
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^1.0.7
  url_launcher: ^5.4.2
  http: ^0.13.0
  flutter_nest:
    git:
      url: ssh://git@github.com/Crowtech/flutter-nest.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
